version: '3.8'

services:

  order-service:
    build: ./order-service
    ports:
      - "8080:8080"
    depends_on:
      - payment-service

  payment-service:
    build: ./payment-service
    ports:
      - "8081:8081"